"""Real Kiwi TCMS integration over XML-RPC -- creates/updates an actual
Product("PulseSOC") -> TestPlan -> TestCase -> TestRun -> TestExecution
hierarchy so qe-guardian's results show up as real, browsable test executions
in Kiwi, not just a log line saying "pushed".

The previous version of this integration POSTed a JSON blob to the XML-RPC
endpoint and treated any HTTP 200 as success -- XML-RPC faults are
themselves returned over HTTP 200, so that check never actually caught a
failure, and no PulseSOC data ever existed in Kiwi. This module replaces
that with genuine XML-RPC calls, verified end-to-end against the live
instance before being wired into test_runner.py.

Kiwi's XML-RPC auth is session-cookie-based: Auth.login() returns a session
key, but the actual auth state lives in the `sessionid`/`csrftoken` cookies
Django sets on the login response -- a plain xmlrpc.client.ServerProxy
doesn't retain cookies between calls, so every call after login would 401
without the CookieTransport below.
"""

import os
import xmlrpc.client

PRODUCT_NAME = "PulseSOC"
PRODUCT_DESCRIPTION = "SOC Executive Command Center (MSSP multi-tenant dashboard)"
VERSION_VALUE = "v2.0"
CATEGORY_NAME = "Automated"
PLAN_NAME = "PulseSOC Automated Regression Suite"
BUILD_NAME = "docker-compose-demo"
PLAN_TYPE_REGRESSION = 11
DEFAULT_PRIORITY = 2  # P2
CASE_STATUS_CONFIRMED = 2
EXEC_STATUS = {"PASS": 4, "FAIL": 5}  # PASSED / FAILED, from TestExecutionStatus


class CookieTransport(xmlrpc.client.SafeTransport):
    """Carries the Django session cookie Auth.login() sets across every
    subsequent XML-RPC call on this connection -- without this, each call is
    unauthenticated even though login() itself reports success."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._cookies = {}

    def send_headers(self, connection, headers):
        if self._cookies:
            connection.putheader("Cookie", "; ".join(f"{k}={v}" for k, v in self._cookies.items()))
        super().send_headers(connection, headers)

    def parse_response(self, response):
        for raw in response.msg.get_all("Set-Cookie") or []:
            key, _, rest = raw.partition("=")
            self._cookies[key.strip()] = rest.split(";")[0].strip()
        return super().parse_response(response)


def _connect(base_url: str, username: str, password: str):
    transport = CookieTransport()
    server = xmlrpc.client.ServerProxy(base_url.rstrip("/") + "/xml-rpc/", transport=transport, allow_none=True)
    server.Auth.login(username, password)
    return server


def _get_or_create(filter_result_getter, create_fn):
    existing = filter_result_getter()
    if existing:
        return existing[0]["id"]
    return create_fn()["id"]


def _get_or_create_product(server):
    return _get_or_create(
        lambda: server.Product.filter({"name": PRODUCT_NAME}),
        lambda: server.Product.create({"name": PRODUCT_NAME, "description": PRODUCT_DESCRIPTION, "classification": 1}),
    )


def _get_or_create_version(server, product_id):
    return _get_or_create(
        lambda: server.Version.filter({"product": product_id, "value": VERSION_VALUE}),
        lambda: server.Version.create({"product": product_id, "value": VERSION_VALUE}),
    )


def _get_or_create_category(server, product_id):
    return _get_or_create(
        lambda: server.Category.filter({"product": product_id, "name": CATEGORY_NAME}),
        lambda: server.Category.create({
            "product": product_id, "name": CATEGORY_NAME,
            "description": "qe-guardian in-process test suite (test_runner.py)",
        }),
    )


def _get_or_create_plan(server, product_id, version_id, author_id):
    return _get_or_create(
        lambda: server.TestPlan.filter({"product": product_id, "name": PLAN_NAME}),
        lambda: server.TestPlan.create({
            "product": product_id,
            "product_version": version_id,
            "type": PLAN_TYPE_REGRESSION,
            "name": PLAN_NAME,
            "text": "Auto-generated by backend/test_runner.py (qe-guardian) on every deploy.",
        }),
    )


def _get_or_create_build(server, version_id):
    return _get_or_create(
        lambda: server.Build.filter({"version": version_id, "name": BUILD_NAME}),
        lambda: server.Build.create({"version": version_id, "name": BUILD_NAME}),
    )


def _get_or_create_case(server, category_id, test_id, name, why):
    summary = f"{test_id}: {name}"
    existing = server.TestCase.filter({"category": category_id, "summary__startswith": f"{test_id}:"})
    if existing:
        case_id = existing[0]["id"]
        if existing[0]["summary"] != summary or existing[0]["text"] != why:
            server.TestCase.update(case_id, {"summary": summary, "text": why})
        return case_id
    case = server.TestCase.create({
        "category": category_id,
        "priority": DEFAULT_PRIORITY,
        "case_status": CASE_STATUS_CONFIRMED,
        "summary": summary,
        "text": why,
    })
    server.TestCase.update(case["id"], {"is_automated": True})
    return case["id"]


def _ensure_case_on_plan(server, plan_id, case_id):
    if not server.TestCase.filter({"plan": plan_id, "id": case_id}):
        server.TestPlan.add_case(plan_id, case_id)


def push_results_to_kiwi(results: list[dict]) -> dict:
    """Creates a fresh TestRun for this invocation and records one
    TestExecution per result, PASSED/FAILED to match. Returns
    {run_id, run_url, cases_synced} for the caller to log."""
    base_url = os.environ["KIWI_TCMS_URL"]
    username = os.environ["KIWI_TCMS_USERNAME"]
    password = os.environ["KIWI_TCMS_PASSWORD"]

    server = _connect(base_url, username, password)
    author_id = server.User.filter({"username": username})[0]["id"]

    product_id = _get_or_create_product(server)
    version_id = _get_or_create_version(server, product_id)
    category_id = _get_or_create_category(server, product_id)
    plan_id = _get_or_create_plan(server, product_id, version_id, author_id)
    build_id = _get_or_create_build(server, version_id)

    passed = sum(1 for r in results if r["status"] == "PASS")
    run = server.TestRun.create({
        "plan": plan_id,
        "build": build_id,
        "summary": f"qe-guardian run -- {passed}/{len(results)} passed",
        "manager": author_id,
    })
    run_id = run["id"]

    for r in results:
        case_id = _get_or_create_case(server, category_id, r["test_id"], r["name"], r["why"])
        _ensure_case_on_plan(server, plan_id, case_id)
        executions = server.TestRun.add_case(run_id, case_id)
        execution_id = executions[0]["id"]
        server.TestExecution.update(execution_id, {
            "status": EXEC_STATUS[r["status"]],
            "tested_by": author_id,
        })
        server.TestExecution.add_comment(execution_id, f"Expected: {r['expected']}\nActual: {r['actual']}")

    return {
        "run_id": run_id,
        "run_url": f"{base_url.rstrip('/')}/runs/{run_id}/",
        "cases_synced": len(results),
        "passed": passed,
        "total": len(results),
    }
